SELECT 1 FROM R5EVENTS EVT , R5ACTIVITIES ACT,R5TRANSLINES TRL , R5ORGANIZATION ORG 
WHERE  EVT.EVT_CODE = ACT.ACT_EVENT
AND    ACT.ACT_EVENT=TRL.TRL_EVENT AND ACT.ACT_ACT=TRL.TRL_ACT
AND    ACT.ACT_HIRE='-' AND ACT.ACT_TASK IS NOT NULL
AND    EVT.EVT_ORG = ORG.ORG_CODE 
AND    ORG.ORG_LOCALE = 'NZ'  
AND    TRL.TRL_RTYPE IN ( 'I', 'MISC' ) 
AND    ((EVT.EVT_ORG NOT IN ('WCC','WBP','WEW') AND EVT.EVT_CLASS IN ('BD','CO'))
         OR (EVT.EVT_ORG IN ('WBP') AND EVT.EVT_CLASS IN ('BD','CO','RN','PS'))
       )
AND    TRL.ROWID =:ROWID 