DECLARE
  STW         R5STANDWORKS%ROWTYPE;
  V_STW         VARCHAR2(3);
  IERRMSG     VARCHAR2(400);
  ERR_VAL EXCEPTION;

  CURSOR CUR_ORIGCOMMENT(VEVT VARCHAR2) IS
    SELECT * FROM R5ADDETAILS
    WHERE ADD_ENTITY='EVNT' AND ADD_CODE = VEVT
    ORDER BY ADD_LINE;
BEGIN
  BEGIN
    SELECT * INTO STW FROM R5STANDWORKS
    WHERE ROWID=:ROWID
      AND NVL(STW_CLASS,'NO') = 'DEFSTW'
      AND NVL(STW_NOTUSED,'-') = '-';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN;
  END;

  SELECT COUNT(1) INTO V_STW
  FROM R5STANDWORKS
  WHERE NVL(STW_CLASS,'NO') = 'DEFSTW'
    AND NVL(STW_NOTUSED,'-') = '-'
    AND STW_JOBTYPE = STW.STW_JOBTYPE
    AND STW_ORG = STW.STW_ORG;
    
  IF V_STW > 1 THEN
    IERRMSG := 'Only 1 active default standard work order per work order type can exist';
    RAISE ERR_VAL;
  END IF;

EXCEPTION
  WHEN ERR_VAL THEN
    RAISE_APPLICATION_ERROR (-20003,
      'ERR/R5STANDWORKS/10/I/' ||SUBSTR(IERRMSG, 1, 500));
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR (SQLCODE,
      'ERR/R5STANDWORKS/10/I/' ||SUBSTR(SQLERRM, 1, 500));
END;