SELECT 1 FROM R5EVENTS EVT , R5TRANSLINES TRL , R5ORGANIZATION ORG 
WHERE  EVT.EVT_CODE = TRL.TRL_EVENT 
AND       EVT.EVT_STATUS IN ( 'C', '55CA' )
AND       EVT.EVT_ORG = ORG.ORG_CODE  
AND       TRL.TRL_RTYPE IN ( 'I', 'MISC' ) 
AND       TRL.ROWID =:ROWID 