SELECT 1 FROM R5EVENTS EVT,R5ACTIVITIES ACT,R5REQUISLINES RQL,R5ORGANIZATION ORG
WHERE EVT.EVT_CODE = ACT.ACT_EVENT 
AND   RQL.RQL_EVENT = ACT.ACT_EVENT AND RQL.RQL_ACT = ACT.ACT_ACT
AND   ACT.ACT_TASK IS NOT NULL 
AND   EVT.EVT_ORG = ORG.ORG_CODE 
AND   ORG.ORG_LOCALE = 'NZ' 
AND   RQL.RQL_STATUS = 'U'
AND   ((EVT.EVT_ORG NOT IN ('WCC','WBP','WEW') AND EVT.EVT_CLASS IN ('BD','CO'))
    OR (EVT.EVT_ORG IN ('WBP') AND EVT.EVT_CLASS IN ('BD','CO','RN','PS'))
    )
AND  RQL.ROWID =:ROWID