SELECT 1 FROM R5EVENTS EVT ,R5ACTIVITIES ACT,r5matlparts MLP , R5ORGANIZATION ORG 
WHERE  EVT.EVT_CODE = ACT.ACT_EVENT
AND    ACT.act_matlist = mlp.mlp_matlist
AND    ACT.ACT_HIRE='-' AND ACT.ACT_TASK IS NOT NULL
AND    EVT.EVT_ORG = ORG.ORG_CODE 
AND    ORG.ORG_LOCALE = 'NZ'  
AND    (EVT.EVT_ORG NOT IN ('WCC','WBP','WEW') AND EVT.EVT_CLASS IN ('BD','CO'))
AND    MLP.ROWID =:ROWID 
