DECLARE 
  IOBJCODE R5OBJUSAGEDEFS.OUD_OBJECT%TYPE;  
  IUOM R5OBJUSAGEDEFS.OUD_UOM%TYPE;
  ICALCDAYS R5OBJUSAGEDEFS.OUD_CALCDAYS%TYPE;
  ITOTALUSAGE R5OBJUSAGEDEFS.OUD_TOTALUSAGE%TYPE;
  IDFLTDAILYUSG R5OBJUSAGEDEFS.OUD_DFLTDAILYUSG%TYPE;
  ILASTREADDATE R5OBJUSAGEDEFS.OUD_LASTREADDATE%TYPE;
  IPARENT R5OBJUSAGEDEFS.OUD_PARENT%TYPE;
  ICHILD R5OBJUSAGEDEFS.OUD_CHILD%TYPE;
  IOBJTYPE R5OBJECTS.OBJ_OBTYPE%TYPE;
  IOBJORG R5OBJECTS.OBJ_ORG%TYPE ;
  
BEGIN 
  SELECT OUD_OBJECT, OUD_UOM, OUD_CALCDAYS, OUD_TOTALUSAGE, OUD_DFLTDAILYUSG, OUD_LASTREADDATE, OUD_PARENT, OUD_CHILD, obj_obtype, OBJ_ORG INTO 
  IOBJCODE, IUOM, ICALCDAYS, ITOTALUSAGE, IDFLTDAILYUSG, ILASTREADDATE, IPARENT, ICHILD, IOBJTYPE, IOBJORG 
  FROM R5OBJUSAGEDEFS OUD , R5OBJECTS OBJ 
  WHERE OUD.ROWID = :ROWID AND OUD_OBJECT = OBJ_CODE AND OUD_OBJECT_ORG = OBJ.OBJ_ORG ; 
  
  IF IOBJTYPE IN ( '05FP' , '06EQ' ) THEN 
    INSERT INTO R5OBJUSAGEDEFS (OUD_OBJECT, OUD_UOM, OUD_CALCDAYS, OUD_TOTALUSAGE, OUD_DFLTDAILYUSG, OUD_LASTREADDATE, OUD_PARENT , OUD_CHILD , OUD_OBJECT_ORG ) 
    SELECT STC_CHILD , IUOM, ICALCDAYS, ITOTALUSAGE, IDFLTDAILYUSG, ILASTREADDATE, IPARENT, ICHILD, IOBJORG FROM R5STRUCTURES
                                    CONNECT BY PRIOR STC_CHILD = STC_PARENT
                                    AND        PRIOR STC_CHILD_ORG = STC_PARENT_ORG
                                    START WITH STC_PARENT = IOBJCODE
                                    AND        STC_PARENT_ORG = IOBJORG 
    AND   NOT EXISTS ( SELECT 1 FROM R5OBJUSAGEDEFS WHERE OUD_OBJECT = STC_CHILD AND OUD_OBJECT_ORG = STC_CHILD_ORG AND OUD_UOM = IUOM) ;
    
  END IF; 
END ;