SELECT 1 FROM R5EVENTS EVT , R5TOOLUSAGE TOU , R5ORGANIZATION ORG 
WHERE  EVT.EVT_CODE = TOU.TOU_EVENT 
AND       EVT.EVT_STATUS IN ( 'C', '55CA')
AND       EVT.EVT_ORG = ORG.ORG_CODE  
AND       TOU.ROWID =:ROWID 