SELECT 1
FROM R5EVENTS EVT, R5BOOKEDHOURS BOO,R5ORGANIZATION ORG,R5PERSONNEL PER
WHERE  EVT.EVT_CODE = BOO.BOO_EVENT 
AND    EVT.EVT_ORG = ORG.ORG_CODE  
AND    BOO.BOO_PERSON IS NOT NULL
AND    BOO.BOO_PERSON = PER.PER_CODE 
AND    ORG.ORG_UDFCHAR09 IS NOT NULL
AND    PER.PER_COSTCODE IS NOT NULL
AND    EVT.EVT_COSTCODE IS NULL
AND    BOO.ROWID =:ROWID 